### ISSUE TITLE
[v2] crash on start

### ISSUE THREAD

**Issue by leethree** [matei-radu/react-native-in-app-browser#75]
There is an exception when I start the app:
```
E/unknown:ReactNative: Exception in native call
    java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=android.support.customtabs.action.CustomTabsService }
        at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1519)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1663)
        at android.app.ContextImpl.bindService(ContextImpl.java:1612)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
        at android.support.customtabs.CustomTabsClient.bindCustomTabsService(CustomTabsClient.java:73)
        at com.mattblock.reactnative.inappbrowser.RNInAppBrowserModule.<init>(RNInAppBrowserModule.kt:51)
        at com.mattblock.reactnative.inappbrowser.RNInAppBrowserPackage.createNativeModules(RNInAppBrowserPackage.kt:17)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1212)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1182)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1120)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:123)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:943)
        at java.lang.Thread.run(Thread.java:764)
```

I'm using RN v0.59.10 and react-native-in-app-browser v2.1.1.

**Comment by matei-radu** [comment]
Thanks for the report.

Can you share some details on the device you are using?

- Emulator of a real device?
- Which version of Android?

Also, did you try to reproduce the error on other devices?

**Comment by leethree** [comment]
I've seen the same error on both emulator and real device. They are all Android 9.0.

**Comment by matei-radu** [comment]
Thank's for the info, I'll have a look at this over the weekend.

**Comment by matei-radu** [comment]
I tried to replicate the error with a fresh RN 0.59 project but without success.

I used multiple devices with different browsers. I even tried with and without the newly added `warmup` and `mayLaunchUrl` methods.

| Device | Android version | WebView implementation |
|:------:|:----:|:----:|
| Samsung Galaxy S9 | 9.0 | 76.0 |
| Emulator x86_64 | 9.0 | 75.0 |
| Sony Xperia XZ | 8.0 | 72.0 |

| CustomTabs supported Browser |
|:----:|
| Google Chrome |
| Google Chrome Beta | 
| Mozilla Firefox |

| Dependency | Version |
|:------:|:-------:|
|@matt-block/react-native-in-app-browser | ^2.1.1 |
| react | 16.8.3 |
| react-native | 0.59.10 |

<hr/>
@leethree could you too try to build a new project and see if you can get the same error?

1. `react-native init InAppBrowserTest --version=0.59.10`
2. `yarn add @matt-block/react-native-in-app-browser@legacy`
3. `react-native link @matt-block/react-native-in-app-browser`
4. Replace `src/App.js` content with the following:

```javascript
import React, {Component} from 'react';
import {StyleSheet, View, Button} from 'react-native';
import {InAppBrowser} from '@matt-block/react-native-in-app-browser';

export default class App extends Component<Props> {
  async open() {
    InAppBrowser.open('https://wikipedia.org')
  }

  async warmup() {
    await InAppBrowser.warmup();
    try {
      await InAppBrowser.mayLaunchUrl('https://wikipedia.org');
      console.warn('Warmup completed');
    } catch (e) {
      console.warn(e);
    }
  }

  render() {
    return (
      <View style={styles.container}>
        <Button title="Warmup" onPress={this.warmup} />
        <Button title="Open Wikipedia" onPress={this.open} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});
```

5. Try to run the application

Let me know how it goes so understand how to move forward 😃

**Comment by leethree** [comment]
I think I found the problem. The device and simulator I'm testing don't have Chrome or Firefox installed. 

`getPreferredBrowserPackageName()` returns `null` in this case. It will lead to crash on next line:
https://github.com/matei-radu/react-native-in-app-browser/blob/4daa836ca171a471e12f74a712e231cebeefea1e/src/android/src/main/kotlin/com/mattblock/reactnative/inappbrowser/RNInAppBrowserModule.kt#L50-L51

We cannot guarantee that all our users have Chrome or Firefox installed. In v2.0.0, `InAppBrowser.open` will fallback to open the system browser, which is what we want. Could you update the library to keep the same behaviour for users without CustomTabs supported browser?

**Comment by matei-radu** [comment]
Aha, understood! Nice finding.

The solution to this appears rather easy to apply so I should be able to make some time over the next days for this.

**Comment by leethree** [comment]
Perfect! Thanks so much.

**Comment by matei-radu** [comment]
@leethree could you try out this RC package and see if the problem is fixed or not?

`@matt-block/react-native-in-app-browser@legacy-next`, or

`@matt-block/react-native-in-app-browser@2.1.2-rc.0`

**Comment by leethree** [comment]
Just tested, it works great!

**Comment by matei-radu** [comment]
I'll make a stable release tomorrow but in the mean time you can continue to use that package.
